default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rb_development

test:
  <<: *default
  database: rb_test

production:
  <<: *default
  database: rb_production
